
on:
  schedule:
    - cron:  "1, * * * *"
  workflow_dispatch:

name: snowfall_report

jobs: 

  create_report:
    runs-on: ubuntu-latest
    env:
       WX_KEY: ${{ secrets.WX_KEY }}

    steps:
    - uses: actions/checkout@v4

    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.5.0'

    - uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: 1.4.515

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 1

    - uses: quarto-dev/quarto-actions/render@v2
      with:
        to: html

    - name: Commit Data
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add index.html
        git commit -m "snowfall" || echo "No changes to commit"
        git push origin || echo "No changes to commit"-
